# This is a basic workflow to help you get started with Actions

name:pkgbase = asciinema
	pkgdesc = Record and share your terminal sessions, the right way
	pkgver = 1.3.0
	pkgrel = 2
	url = https://asciinema.org/
	arch = any
	license = GPL3
	depends = python
	source = https://github.com/asciinema/asciinema/archive/v1.3.0.tar.gz
	sha1sums = cbfec02e9b0cfa47ae8f8793032e6f4b8eb76d40

pkgname = asciinema



# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
